# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sections
                                 A QGIS plugin
 Creates a section polygon layer from a point layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-01
        copyright            : (C) 2024 by Marek Zygadło
        email                : m.zygadlo@gis4.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sections class from file Sections.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sections import Sections
    return Sections(iface)
